import Header from "../components/Header"
import Footer from "../components/Footer"
import SignForm from '../components/users/signForm';
import { Button } from 'react-bootstrap';
import Link from 'next/link';

const Authentication: React.FC = () => {
  return (
    <>
      <Header />
      <main className="min-h-screen flex items-center justify-center">
        <section className="max-w-md w-full p-4 bg-white rounded-lg shadow-lg">
          <SignForm method="login" header="Login" />
          <div className="mt-4 text-center">
            <p className="text-gray-600">
              Don't have an account?{' '}
              <Button>
                <Link href="/signup">Sign up</Link>
              </Button>
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Authentication;

// import Head from 'next/head';
// import { Inter } from 'next/font/google'
// import Header from "../components/Header"
// import Footer from "../components/Footer"
// import SignForm from '../components/users/loginForm'
// import styles from '../styles/Home.module.css'
// import Link from 'next/link';

// const inter = Inter({ subsets: ['latin'] })


//  const Authentication: React.FC = () => {
//     return (
//         <>
//         <Head>
//             <title>Home</title>
//           </Head>
//                 <main className="vh-100">
//                <h4 className="text-center">Authentication</h4>
//                 <section className="row justify-content-evenly">
//                     <SignForm method="login" header="Login"/>
//                     <Link href="/signup">No account yet?</Link>
//                 </section>
//             </main> 
//         </>
      
//       )  
// }
 
// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Doktorspraktijk</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//       <Authentication></Authentication>
//       <div className={`${styles.title} ${inter.className}`}>
//         <div className={styles.center}>
//         <h1>Doktorspraktijk</h1>
//         </div>
//       <div className={styles.center}>
//         <p>
//           Welkom bij de Doktorspraktijk. Hier kunt u terecht voor al uw medische vragen.
//         </p>
//       </div>
//       </div>
//       <div className={`${styles.main} ${inter.className}`}>
//         <div className={styles.grid}>
//           <Link
//             href="/doktors"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Doktors <span>-&gt;</span>
//             </h2>
//             <p>
//               Vindt informatie over onze Doktors.
//             </p>
//           </Link>

//           <Link
//             href="/user"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               User Overview <span>-&gt;</span>
//             </h2>
//             <p>
//               User Overview admin
//             </p>
//           </Link>

//           <Link
//             href="/medicalHistory"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Medische gegevens <span>-&gt;</span>
//             </h2>
//             <p>
//               Jouw medische gegevens inzien.
//             </p>
//           </Link>

//           <Link
//             href="/appointment"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Maak een afspraak <span>-&gt;</span>
//             </h2>
//             <p>
//               Maak een afspraak met 1 van onze Doktors.
//             </p>
//           </Link>
//         </div>
//       </div>
//       <div className={`${styles.main} ${inter.className}`}>
//       </div>
//       </main>
//     </>
//   )
// }
